services:

  # Production service
  frontend:
    build:
      context: .
      target: production-stage
    container_name: vue-chat-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped

  # Development service with hot-reloading
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-chat-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  chat-network:
    name: chat-network
    driver: bridge