services:
  # For production:
  frontend:
    build:
      context: .
      target: production-stage
    container_name: vue-chat-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./config/.env
    restart: unless-stopped
    networks:
      - chat-network
    command: node vueBaseAppServer.js

  # Development service for hot-reloading
  frontend-dev:
    build:
      context: .
      target: build-stage
    container_name: vue-chat-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - ./config/.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - chat-network

networks:
  chat-network:
    name: chat-network
    driver: bridge